// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   8

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    staking_contract
    (
        init => init
        stake => stake
        unstake => unstake
        claim_rewards => claim_rewards
        getStakingPosition => get_staking_position
        getStakedAddresses => get_staked_addresses
        getApy => get_apy
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
